// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbmzwtpepcmrispmuxkp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdibXp3dHBlcGNtcmlzcG11eGtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3OTI4MTcsImV4cCI6MjA1NzM2ODgxN30.gC7NGueJBARBjWXBKFleM3YiZn9TZqOVZjqrhEAin7A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);